/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs_trial;

import CSV.CSV;
import javax.swing.JOptionPane;
import trreeclass.BinaryHeap;
import trreeclass.List;

/**
 *
 * @author Dell
 */
public class DeleteUserUI extends javax.swing.JFrame {

    private String path;
    private List usuarios;
    private System_Usuarios SU;
    private BinaryHeap bh;
    private TimerUI time;
    /**
     * Creates new form DeleteUserUI
     */
    public DeleteUserUI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title4 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        DeleteUserTF = new javax.swing.JTextField();
        DeleteUserButt = new javax.swing.JButton();
        BackToOSButt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        Title4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Title4.setForeground(new java.awt.Color(255, 255, 255));
        Title4.setText("Delete User");
        getContentPane().add(Title4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 210, 60));

        lab1.setForeground(new java.awt.Color(255, 255, 255));
        lab1.setText("Indique el nombre del usuario que quiera eliminar:");
        getContentPane().add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 720, 40));
        getContentPane().add(DeleteUserTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 570, 50));

        DeleteUserButt.setBackground(new java.awt.Color(255, 153, 153));
        DeleteUserButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        DeleteUserButt.setText("Eliminar usuario");
        DeleteUserButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserButtActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteUserButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 350, 60));

        BackToOSButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BackToOSButt.setText("volver");
        BackToOSButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToOSButtActionPerformed(evt);
            }
        });
        getContentPane().add(BackToOSButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 130, 40));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIs_trial/DeleteUserBackGround.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteUserButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserButtActionPerformed
      String nombre = DeleteUserTF.getText();
      CSV C = new CSV();
      C.DeleteCSV(getPath(), C.DeleteLine(getPath(),nombre));
      JOptionPane.showMessageDialog(null, "El usuario se borró exitosamente");
    }//GEN-LAST:event_DeleteUserButtActionPerformed

    private void BackToOSButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToOSButtActionPerformed
        this.setVisible(false);
        OperativeSistemUI ventana = new OperativeSistemUI();
        ventana.setPath(getPath());
        ventana.setUsuarios(getUsuarios());
        ventana.setSU(getSU());
        ventana.setBh(getBh());
        ventana.setTime(getTime());
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackToOSButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteUserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToOSButt;
    private javax.swing.JButton DeleteUserButt;
    private javax.swing.JTextField DeleteUserTF;
    private javax.swing.JLabel Title4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab1;
    // End of variables declaration//GEN-END:variables

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public List getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(List usuarios) {
        this.usuarios = usuarios;
    }

    public System_Usuarios getSU() {
        return SU;
    }

    public void setSU(System_Usuarios SU) {
        this.SU = SU;
    }

    public BinaryHeap getBh() {
        return bh;
    }

    public void setBh(BinaryHeap bh) {
        this.bh = bh;
    }

    public TimerUI getTime() {
        return time;
    }

    public void setTime(TimerUI time) {
        this.time = time;
    }

    

}
