/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs_trial;

import CSV.CSV;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import trreeclass.BinaryHeap;

/**
 *
 * @author Dell
 */
public class LoadArchiveUI extends javax.swing.JFrame {

    /**
     * Creates new form LoadArchiveUI
     */
    public LoadArchiveUI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        LoadArchiveButt = new javax.swing.JButton();
        Background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        Title1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("Proyecto 2: Cola de impresión con montículo binario");
        getContentPane().add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 680, 60));

        lab1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lab1.setForeground(new java.awt.Color(255, 255, 255));
        lab1.setText("Bienvenido, por favor seleccione un archivo de tipo CSV para iniciar el programa");
        getContentPane().add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 540, 50));

        LoadArchiveButt.setBackground(new java.awt.Color(255, 51, 255));
        LoadArchiveButt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LoadArchiveButt.setText("Cargar archivo");
        LoadArchiveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadArchiveButtActionPerformed(evt);
            }
        });
        getContentPane().add(LoadArchiveButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 430, 70));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIs_trial/BackGroundLoad.png"))); // NOI18N
        getContentPane().add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadArchiveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadArchiveButtActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("CSV","csv");
        jFileChooser.setFileFilter(filtrado);
        int respuesta = jFileChooser.showOpenDialog(this);
        if (respuesta==JFileChooser.APPROVE_OPTION) {
            String Ruta = jFileChooser.getSelectedFile().getPath();
            JOptionPane.showMessageDialog(null, "El archivo se leyó ");
            CSV c=new CSV();
            BinaryHeap bin = new BinaryHeap(); 
            OperativeSistemUI ventanaOS = new OperativeSistemUI();
            System_Usuarios ventanaSU = new System_Usuarios();
            TimerUI timer = new TimerUI();
            timer.setVisible(true);
            ventanaSU.setPath(Ruta);
            ventanaSU.setVisible(true);
            ventanaOS.setPath(Ruta);
            ventanaOS.setUsuarios(c.leer(Ruta));
            ventanaOS.setSU(ventanaSU);
            ventanaOS.setBh(bin);
            ventanaOS.setTime(timer);
            ventanaOS.setVisible(true);
            this.dispose();
        } 
    }//GEN-LAST:event_LoadArchiveButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadArchiveUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background1;
    private javax.swing.JButton LoadArchiveButt;
    private javax.swing.JLabel Title1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab1;
    // End of variables declaration//GEN-END:variables
}
