/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs;

import Tree_clases.HashTable;
import Tree_clases.List;
import Tree_clases.Node_Document;
import Tree_clases.Nodo_list;
import Tree_clases.Object_Document;
import Tree_clases.Usuario;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author Dell
 */
public class ArchivesOperationsUI extends javax.swing.JFrame {
    private Timer myTimer;
    public int segundos = 0;
    private String path;
    public static HashTable usuarios;
    /**
     * Creates new form ArchivesOperationsUI
     */
    public ArchivesOperationsUI(HashTable h) {
        this.usuarios = h;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        myTimer = new Timer(1000, (ActionEvent e) -> {
            StartTimer();
        });
        myTimer.start();
        
    }
    private void StartTimer(){
        UpdateTime();
        
        
    }
    
    private void UpdateTime(){
        segundos++;
    }
    
    public String getPath(){
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public HashTable getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(HashTable usuarios) {
        this.usuarios = usuarios;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Title4 = new javax.swing.JLabel();
        AddArchiveNameTF = new javax.swing.JTextField();
        Lab1 = new javax.swing.JLabel();
        RemoveArchiveUNameTF = new javax.swing.JTextField();
        Lab2 = new javax.swing.JLabel();
        Lab3 = new javax.swing.JLabel();
        SendArchiveTF = new javax.swing.JTextField();
        AddArchiveButt = new javax.swing.JButton();
        RemoveArchiveButt = new javax.swing.JButton();
        SendArchiveButt = new javax.swing.JButton();
        BackToSOButt = new javax.swing.JButton();
        AddArchiveUNameTF = new javax.swing.JTextField();
        AddArchiveSizeTF = new javax.swing.JTextField();
        AddArchiveTypeTF = new javax.swing.JTextField();
        AddDocuPriorityButt = new javax.swing.JToggleButton();
        RemoveArchiveNameTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        Title4.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        Title4.setForeground(new java.awt.Color(255, 255, 255));
        Title4.setText("Operaciones de archivos");
        getContentPane().add(Title4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 310, 40));

        AddArchiveNameTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddArchiveNameTF.setForeground(new java.awt.Color(153, 153, 153));
        AddArchiveNameTF.setText("Ej: factura_Enero2");
        AddArchiveNameTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddArchiveNameTFMouseClicked(evt);
            }
        });
        getContentPane().add(AddArchiveNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 50));

        Lab1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Lab1.setForeground(new java.awt.Color(255, 255, 255));
        Lab1.setText("Introducir el nombre del archivo, nombre del usuario, prioridad del archivo,  tamaño del archivo (KB) y tipo del archivo y si es prioritario o no:");
        getContentPane().add(Lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 740, 40));

        RemoveArchiveUNameTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RemoveArchiveUNameTF.setForeground(new java.awt.Color(153, 153, 153));
        RemoveArchiveUNameTF.setText("Ej: Juan1789");
        RemoveArchiveUNameTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveArchiveUNameTFMouseClicked(evt);
            }
        });
        getContentPane().add(RemoveArchiveUNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 310, 50));

        Lab2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Lab2.setForeground(new java.awt.Color(255, 255, 255));
        Lab2.setText("Introducir el nombre del usuario y el del archivo, tenga en cuenta que este archivo no puede haber sido enviado a la cola de impresión:");
        getContentPane().add(Lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 780, 30));

        Lab3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Lab3.setForeground(new java.awt.Color(255, 255, 255));
        Lab3.setText("Introducir el nombre del documento para que este sea enviado a la cola de impresión:");
        getContentPane().add(Lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 740, 30));

        SendArchiveTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SendArchiveTF.setForeground(new java.awt.Color(153, 153, 153));
        SendArchiveTF.setText("Ej: factura_Enero2");
        SendArchiveTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendArchiveTFMouseClicked(evt);
            }
        });
        getContentPane().add(SendArchiveTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 580, 50));

        AddArchiveButt.setBackground(new java.awt.Color(102, 255, 102));
        AddArchiveButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AddArchiveButt.setText("Añadir documento");
        AddArchiveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddArchiveButtActionPerformed(evt);
            }
        });
        getContentPane().add(AddArchiveButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 210, 50));

        RemoveArchiveButt.setBackground(new java.awt.Color(255, 102, 102));
        RemoveArchiveButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        RemoveArchiveButt.setText("Eliminar documento");
        RemoveArchiveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveArchiveButtActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveArchiveButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 240, 50));

        SendArchiveButt.setBackground(new java.awt.Color(255, 255, 153));
        SendArchiveButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SendArchiveButt.setText("Enviar documento");
        SendArchiveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendArchiveButtActionPerformed(evt);
            }
        });
        getContentPane().add(SendArchiveButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 230, 50));

        BackToSOButt.setBackground(new java.awt.Color(51, 255, 255));
        BackToSOButt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BackToSOButt.setText("Volver a SO");
        BackToSOButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToSOButtActionPerformed(evt);
            }
        });
        getContentPane().add(BackToSOButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 160, 50));

        AddArchiveUNameTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddArchiveUNameTF.setForeground(new java.awt.Color(153, 153, 153));
        AddArchiveUNameTF.setText("Ej: Juan1789");
        AddArchiveUNameTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddArchiveUNameTFMouseClicked(evt);
            }
        });
        getContentPane().add(AddArchiveUNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 200, 50));

        AddArchiveSizeTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddArchiveSizeTF.setForeground(new java.awt.Color(153, 153, 153));
        AddArchiveSizeTF.setText("Ej: 58");
        AddArchiveSizeTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddArchiveSizeTFMouseClicked(evt);
            }
        });
        getContentPane().add(AddArchiveSizeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 60, 50));

        AddArchiveTypeTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddArchiveTypeTF.setForeground(new java.awt.Color(153, 153, 153));
        AddArchiveTypeTF.setText("Ej: PDF");
        AddArchiveTypeTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddArchiveTypeTFMouseClicked(evt);
            }
        });
        getContentPane().add(AddArchiveTypeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 70, 50));

        AddDocuPriorityButt.setBackground(new java.awt.Color(255, 182, 182));
        AddDocuPriorityButt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddDocuPriorityButt.setText("NO");
        AddDocuPriorityButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDocuPriorityButtActionPerformed(evt);
            }
        });
        getContentPane().add(AddDocuPriorityButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 70, 50));

        RemoveArchiveNameTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RemoveArchiveNameTF.setForeground(new java.awt.Color(153, 153, 153));
        RemoveArchiveNameTF.setText("Ej: factura_Enero2");
        RemoveArchiveNameTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveArchiveNameTFMouseClicked(evt);
            }
        });
        getContentPane().add(RemoveArchiveNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 240, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIs/BackgroundArchiveOperations.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddArchiveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddArchiveButtActionPerformed
        String user = AddArchiveUNameTF.getText();
        String nombre = AddArchiveNameTF.getText();
        String tipo = AddArchiveTypeTF.getText();
        String tamaño = AddArchiveSizeTF.getText();
        int size=Integer.parseInt(tamaño);
        Usuario pAux = usuarios.search(user);
        Object_Document document = new Object_Document(nombre,tipo,size);
        
        if (pAux != null){
            pAux.getDocumentos().AddDocumentAtEnd(nombre,tipo,size,0,false);
        }
        
        JOptionPane.showMessageDialog(null, "Documento añadido exitosamente");
        System.out.println(user);
        
    }//GEN-LAST:event_AddArchiveButtActionPerformed

    private void RemoveArchiveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveArchiveButtActionPerformed
        String user = RemoveArchiveUNameTF.getText();
        String nombre = RemoveArchiveNameTF.getText();
        Usuario pAux = usuarios.search(user);
        while (pAux!=null){
            if (pAux.getNombre().equalsIgnoreCase(user)){
                pAux.getDocumentos().DeleteDocument(nombre);
                break;
            }
            pAux=pAux.getpNext();
        }
    }//GEN-LAST:event_RemoveArchiveButtActionPerformed

    private void SendArchiveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendArchiveButtActionPerformed
        //
    }//GEN-LAST:event_SendArchiveButtActionPerformed

    private void BackToSOButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToSOButtActionPerformed
        this.setVisible(false);
        OperativeSistemUI ventanaso = new OperativeSistemUI(usuarios);
        ventanaso.setVisible(true);
    }//GEN-LAST:event_BackToSOButtActionPerformed

    private void AddDocuPriorityButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDocuPriorityButtActionPerformed
        if (AddDocuPriorityButt.isSelected() == true){
            AddDocuPriorityButt.setText("SI");
        }
        else{
            AddDocuPriorityButt.setBackground(new Color(255, 182, 182));
            AddDocuPriorityButt.setText("NO");
        }
    }//GEN-LAST:event_AddDocuPriorityButtActionPerformed

    private void AddArchiveNameTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddArchiveNameTFMouseClicked
        if (!AddArchiveNameTF.equals(AddArchiveNameTF.getText())) {
            AddArchiveNameTF.setText("");
            AddArchiveNameTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_AddArchiveNameTFMouseClicked

    private void AddArchiveUNameTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddArchiveUNameTFMouseClicked
        if (!AddArchiveUNameTF.equals(AddArchiveUNameTF.getText())) {
            AddArchiveUNameTF.setText("");
            AddArchiveUNameTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_AddArchiveUNameTFMouseClicked

    private void AddArchiveSizeTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddArchiveSizeTFMouseClicked
        if (!AddArchiveSizeTF.equals(AddArchiveSizeTF.getText())) {
            AddArchiveSizeTF.setText("");
            AddArchiveSizeTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_AddArchiveSizeTFMouseClicked

    private void AddArchiveTypeTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddArchiveTypeTFMouseClicked
        if (!AddArchiveTypeTF.equals(AddArchiveTypeTF.getText())) {
            AddArchiveTypeTF.setText("");
            AddArchiveTypeTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_AddArchiveTypeTFMouseClicked

    private void RemoveArchiveUNameTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveArchiveUNameTFMouseClicked
        if (!RemoveArchiveUNameTF.equals(RemoveArchiveUNameTF.getText())) {
            RemoveArchiveUNameTF.setText("");
            RemoveArchiveUNameTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_RemoveArchiveUNameTFMouseClicked

    private void RemoveArchiveNameTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveArchiveNameTFMouseClicked
        if (!RemoveArchiveNameTF.equals(RemoveArchiveNameTF.getText())) {
            RemoveArchiveNameTF.setText("");
            RemoveArchiveNameTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_RemoveArchiveNameTFMouseClicked

    private void SendArchiveTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendArchiveTFMouseClicked
        if (!SendArchiveTF.equals(SendArchiveTF.getText())) {
            SendArchiveTF.setText("");
            SendArchiveTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_SendArchiveTFMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArchivesOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArchivesOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArchivesOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArchivesOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArchivesOperationsUI(usuarios).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddArchiveButt;
    private javax.swing.JTextField AddArchiveNameTF;
    private javax.swing.JTextField AddArchiveSizeTF;
    private javax.swing.JTextField AddArchiveTypeTF;
    private javax.swing.JTextField AddArchiveUNameTF;
    private javax.swing.JToggleButton AddDocuPriorityButt;
    private javax.swing.JButton BackToSOButt;
    private javax.swing.JLabel Lab1;
    private javax.swing.JLabel Lab2;
    private javax.swing.JLabel Lab3;
    private javax.swing.JButton RemoveArchiveButt;
    private javax.swing.JTextField RemoveArchiveNameTF;
    private javax.swing.JTextField RemoveArchiveUNameTF;
    private javax.swing.JButton SendArchiveButt;
    private javax.swing.JTextField SendArchiveTF;
    private javax.swing.JLabel Title4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
