/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs;

/**
 *
 * @author Dell
 */
public class LoadArchiveUI extends javax.swing.JFrame {

    /**
     * Creates new form LoadArchive
     */
    public LoadArchiveUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        Lab1 = new javax.swing.JLabel();
        Lab2 = new javax.swing.JLabel();
        LoadArchiveButt = new javax.swing.JButton();
        PredetArchiveButt = new javax.swing.JButton();
        Background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        Title1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("Proyecto 2: Cola de impresión con montículo binario");
        getContentPane().add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 660, 60));

        Lab1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab1.setForeground(new java.awt.Color(255, 255, 255));
        Lab1.setText("Por favor seleccione la opción que desea realizar, la opción de utilizar un archivo predeterminado utilizará");
        getContentPane().add(Lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 880, 40));

        Lab2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab2.setForeground(new java.awt.Color(255, 255, 255));
        Lab2.setText("un archivo de tipo CSV por defecto");
        getContentPane().add(Lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 580, 40));

        LoadArchiveButt.setBackground(new java.awt.Color(102, 102, 255));
        LoadArchiveButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LoadArchiveButt.setText("Cargar archivo de tipo CSV");
        LoadArchiveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadArchiveButtActionPerformed(evt);
            }
        });
        getContentPane().add(LoadArchiveButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 320, 70));

        PredetArchiveButt.setBackground(new java.awt.Color(102, 102, 255));
        PredetArchiveButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        PredetArchiveButt.setText("Utilizar archivo predeterminado");
        PredetArchiveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PredetArchiveButtActionPerformed(evt);
            }
        });
        getContentPane().add(PredetArchiveButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 340, 70));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIs/BackGroundLoad.png"))); // NOI18N
        getContentPane().add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadArchiveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadArchiveButtActionPerformed
        
        
        
        
        //Visualización de la segunda ventana
        this.setVisible(false);
        OperativeSistemUI ventanaoperative = new OperativeSistemUI();
        ventanaoperative.setVisible(true);
    }//GEN-LAST:event_LoadArchiveButtActionPerformed

    private void PredetArchiveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PredetArchiveButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PredetArchiveButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadArchiveUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Lab1;
    private javax.swing.JLabel Lab2;
    private javax.swing.JButton LoadArchiveButt;
    private javax.swing.JButton PredetArchiveButt;
    private javax.swing.JLabel Title1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
