/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs;

import CSV.CSV;
import Tree_clases.HashTable;
import Tree_clases.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Dell
 */
public class LoadArchiveUI extends javax.swing.JFrame {

    /**
     * Creates new form LoadArchive
     */
    public LoadArchiveUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    private String path;
    public static HashTable usuarios;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        Lab1 = new javax.swing.JLabel();
        LoadArchiveButt = new javax.swing.JButton();
        Background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        Title1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("Proyecto 2: Cola de impresión con montículo binario");
        getContentPane().add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 660, 60));

        Lab1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab1.setForeground(new java.awt.Color(255, 255, 255));
        Lab1.setText("Bienvenido al proyecto de la cola de impresión con montículo binario, por favor cargue un archivo CSV");
        getContentPane().add(Lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 880, 40));

        LoadArchiveButt.setBackground(new java.awt.Color(102, 102, 255));
        LoadArchiveButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LoadArchiveButt.setText("Cargar archivo de tipo CSV");
        LoadArchiveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadArchiveButtActionPerformed(evt);
            }
        });
        getContentPane().add(LoadArchiveButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 320, 70));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIs/BackGroundLoad.png"))); // NOI18N
        getContentPane().add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadArchiveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadArchiveButtActionPerformed
        //Cargar archivo
        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("CSV","csv");
        jFileChooser.setFileFilter(filtrado);
        
        int respuesta = jFileChooser.showOpenDialog(this);
        
        if (respuesta==JFileChooser.APPROVE_OPTION) {
            String Ruta = jFileChooser.getSelectedFile().getPath();
            JOptionPane.showMessageDialog(null, "El archivo se cargó correctamente");
            CSV c=new CSV();
            usuarios = c.leer(Ruta);
            OperativeSistemUI ventana = new OperativeSistemUI(usuarios);

            ventana.setUsuarios(usuarios);
            ventana.setVisible(true);
            this.dispose();
        }else{
            this.setVisible(false);
            LoadArchiveUI ventanaload = new LoadArchiveUI();
            ventanaload.setVisible(true);
            JOptionPane.showMessageDialog(null, "El archivo no es del tipo correcto");
        }
        
        
        
        //Visualización de la segunda ventana
        this.setVisible(false);
        OperativeSistemUI ventanaoperative = new OperativeSistemUI(usuarios);
        ventanaoperative.setVisible(true);
    }//GEN-LAST:event_LoadArchiveButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadArchiveUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Lab1;
    private javax.swing.JButton LoadArchiveButt;
    private javax.swing.JLabel Title1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public HashTable getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(HashTable usuarios) {
        this.usuarios = usuarios;
    }
}
