/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs;

import java.awt.Color;
import CSV.CSV;
import Tree_clases.HashTable;
import Tree_clases.Usuario;
import java.awt.event.MouseEvent;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;


/**
 *
 * @author Dell
 */
public class UsersOperationsUI extends javax.swing.JFrame {
    public static HashTable h;
    CSV csv_methods ;

    /**
     * Creates new form UsersOperationsUI
     */
    
    public javax.swing.JTextField getPrioridad(){
        return AddUserPrioTF;
    }
    
    private String path;
    
    public String getPath(){
        return path;
    }
    
    public void setPath(String path){
        this.path = path;
    }
    public boolean VerifyChoice(String numericchoice){
        return numericchoice.matches("[1-3]");
    }
    public UsersOperationsUI(HashTable h) {
        initComponents();
        this.h = h;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.csv_methods = new CSV();
//        this.h = csv_methods.getHashTable(getPath());
    }
    
    public void Mouseclicked(MouseEvent e){
        AddUserNameTF.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title3 = new javax.swing.JLabel();
        AddUserNameTF = new javax.swing.JTextField();
        RemoveUserTF = new javax.swing.JTextField();
        Lab1 = new javax.swing.JLabel();
        Lab2 = new javax.swing.JLabel();
        AddUserButt = new javax.swing.JButton();
        RemoveUserButt = new javax.swing.JButton();
        BackToSOButt = new javax.swing.JButton();
        AddUserPrioTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        Title3.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        Title3.setForeground(new java.awt.Color(255, 255, 255));
        Title3.setText("Operaciones con usuarios");
        getContentPane().add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 340, 50));

        AddUserNameTF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AddUserNameTF.setForeground(new java.awt.Color(153, 153, 153));
        AddUserNameTF.setText("Ej: Juan1789");
        AddUserNameTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserNameTFMouseClicked(evt);
            }
        });
        AddUserNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserNameTFActionPerformed(evt);
            }
        });
        getContentPane().add(AddUserNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 370, 50));

        RemoveUserTF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        RemoveUserTF.setForeground(new java.awt.Color(153, 153, 153));
        RemoveUserTF.setText("Ej: Simon287");
        RemoveUserTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveUserTFMouseClicked(evt);
            }
        });
        getContentPane().add(RemoveUserTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 560, 50));

        Lab1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab1.setForeground(new java.awt.Color(255, 255, 255));
        Lab1.setText("Especificar el nombre del usuario seguido de la prioridad de este, (1=alta, 2=media, 3=baja):");
        getContentPane().add(Lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 750, 40));

        Lab2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab2.setForeground(new java.awt.Color(255, 255, 255));
        Lab2.setText("Especificar el nombre del usuario:");
        getContentPane().add(Lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 420, 40));

        AddUserButt.setBackground(new java.awt.Color(102, 255, 102));
        AddUserButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AddUserButt.setText("Añadir usuario");
        AddUserButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserButtActionPerformed(evt);
            }
        });
        getContentPane().add(AddUserButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 210, 50));

        RemoveUserButt.setBackground(new java.awt.Color(255, 102, 102));
        RemoveUserButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        RemoveUserButt.setText("Eliminar usuario");
        RemoveUserButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveUserButtActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveUserButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 210, 50));

        BackToSOButt.setBackground(new java.awt.Color(102, 255, 255));
        BackToSOButt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BackToSOButt.setText("Volver a SO");
        BackToSOButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToSOButtActionPerformed(evt);
            }
        });
        getContentPane().add(BackToSOButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 150, 50));

        AddUserPrioTF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AddUserPrioTF.setForeground(new java.awt.Color(153, 153, 153));
        AddUserPrioTF.setText("Ej: 1");
        AddUserPrioTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserPrioTFMouseClicked(evt);
            }
        });
        AddUserPrioTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserPrioTFActionPerformed(evt);
            }
        });
        getContentPane().add(AddUserPrioTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIs/BackgroundUsersOperations.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToSOButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToSOButtActionPerformed
        this.setVisible(false);
        OperativeSistemUI ventanaso = new OperativeSistemUI(h);
        ventanaso.setVisible(true);
        
    }//GEN-LAST:event_BackToSOButtActionPerformed

    private void AddUserButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserButtActionPerformed
        AddUserNameTF.setForeground(new java.awt.Color(153, 153, 153));
        AddUserPrioTF.setForeground(new java.awt.Color(153, 153, 153));
        Usuario existe = h.search(AddUserNameTF.getText());
        if (AddUserNameTF.getText().equalsIgnoreCase("") || existe != null){
           if (AddUserNameTF.getText().equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(null, "Por favor ingrese un nombre válido");
            AddUserNameTF.setText("");
            AddUserPrioTF.setText("");
           }else if (existe != null){
               JOptionPane.showMessageDialog(null, "El usuario ya existe, por favor introduzca otro usuario");
               AddUserNameTF.setText("");
               AddUserPrioTF.setText("");
           }
        }else{
        String nombre=AddUserNameTF.getText();
        String Priority = AddUserPrioTF.getText();
        String numericchoice;
        if(VerifyChoice(AddUserPrioTF.getText().trim()) == false){
            JOptionPane.showMessageDialog(null, "Los datos no son correctos, por favor introduzca una prioridad válida");
            AddUserNameTF.setText("");
            AddUserPrioTF.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "STRING OBTENIDO");
            JOptionPane.showMessageDialog(null, "El usuario se añadió exitosamente");
            JOptionPane.showMessageDialog(null, "EL CSV SE HA MODIFICADO");
            AddUserNameTF.setText("");
            AddUserPrioTF.setText("");
        }
        numericchoice = AddUserPrioTF.getText();
        Usuario user = new Usuario(nombre, Integer.parseInt(Priority));
        h.Add(user);
        CSV C = new CSV();
//        C.ModifyCSV(getPath(),csv_methods.getString(getPath()), nombre,numericchoice);

        }
    }//GEN-LAST:event_AddUserButtActionPerformed

    private void AddUserPrioTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserPrioTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUserPrioTFActionPerformed

    private void RemoveUserButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveUserButtActionPerformed
        Usuario existe = h.search(AddUserNameTF.getText());
  
        if (AddUserNameTF.getText().equalsIgnoreCase("") || existe != null){
           if (AddUserNameTF.getText().equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(null, "Por favor ingrese un nombre válido");
            AddUserNameTF.setText("");
            AddUserPrioTF.setText("");
           }else if (existe != null){
               JOptionPane.showMessageDialog(null, "El usuario se eliminó exitosamente");
               AddUserNameTF.setText("");
               AddUserPrioTF.setText("");
               //h.delete(user);
               CSV C = new CSV();
               h.guardar(C, path);
           }
        }
    
               
               
               
        String nombre = RemoveUserTF.getText();
        JOptionPane.showMessageDialog(null, "EL USUARIO SE ELIMINÓ EXITOSAMENTE");
        CSV csv_methods = new CSV();
        csv_methods.DeleteCSV(getPath(), csv_methods.DeleteLine(getPath(), nombre));
        JOptionPane.showMessageDialog(null, "EL CSV SE HA ACTUALIZADO");
    }//GEN-LAST:event_RemoveUserButtActionPerformed

    private void AddUserNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserNameTFActionPerformed
        //
    }//GEN-LAST:event_AddUserNameTFActionPerformed

    private void AddUserNameTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserNameTFMouseClicked
        if (!AddUserNameTF.equals(AddUserNameTF.getText())) {
            AddUserNameTF.setText("");
            AddUserNameTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_AddUserNameTFMouseClicked

    private void AddUserPrioTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserPrioTFMouseClicked
        if (!AddUserPrioTF.equals(AddUserPrioTF.getText())) {
            AddUserPrioTF.setText("");
            AddUserPrioTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_AddUserPrioTFMouseClicked

    private void RemoveUserTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveUserTFMouseClicked
        if (!RemoveUserTF.equals(RemoveUserTF.getText())) {
            RemoveUserTF.setText("");
            RemoveUserTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_RemoveUserTFMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersOperationsUI(h).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUserButt;
    private javax.swing.JTextField AddUserNameTF;
    private javax.swing.JTextField AddUserPrioTF;
    private javax.swing.JButton BackToSOButt;
    private javax.swing.JLabel Lab1;
    private javax.swing.JLabel Lab2;
    private javax.swing.JButton RemoveUserButt;
    private javax.swing.JTextField RemoveUserTF;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
