/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs;


/**
 *
 * @author Dell
 */
public class UsersOperationsUI extends javax.swing.JFrame {

    /**
     * Creates new form UsersOperationsUI
     */
    
    public javax.swing.JTextField getPrioridad(){
        return AddUserPrioTF;
    }
    public UsersOperationsUI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title3 = new javax.swing.JLabel();
        AddUserNameTF = new javax.swing.JTextField();
        RemoveUserTF = new javax.swing.JTextField();
        Lab1 = new javax.swing.JLabel();
        Lab2 = new javax.swing.JLabel();
        AddUserButt = new javax.swing.JButton();
        RemoveUserButt = new javax.swing.JButton();
        BackToSOButt = new javax.swing.JButton();
        AddUserPrioTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        Title3.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        Title3.setForeground(new java.awt.Color(255, 255, 255));
        Title3.setText("Operaciones con usuarios");
        getContentPane().add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 340, 50));
        getContentPane().add(AddUserNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 370, 50));
        getContentPane().add(RemoveUserTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 560, 50));

        Lab1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab1.setForeground(new java.awt.Color(255, 255, 255));
        Lab1.setText("Especificar el nombre del usuario seguido de la prioridad de este:");
        getContentPane().add(Lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 540, 40));

        Lab2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lab2.setForeground(new java.awt.Color(255, 255, 255));
        Lab2.setText("Especificar el nombre del usuario:");
        getContentPane().add(Lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 420, 40));

        AddUserButt.setBackground(new java.awt.Color(102, 255, 102));
        AddUserButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AddUserButt.setText("Añadir usuario");
        AddUserButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserButtActionPerformed(evt);
            }
        });
        getContentPane().add(AddUserButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 210, 50));

        RemoveUserButt.setBackground(new java.awt.Color(255, 102, 102));
        RemoveUserButt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        RemoveUserButt.setText("Eliminar usuario");
        getContentPane().add(RemoveUserButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 210, 50));

        BackToSOButt.setBackground(new java.awt.Color(102, 255, 255));
        BackToSOButt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BackToSOButt.setText("Volver a SO");
        BackToSOButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToSOButtActionPerformed(evt);
            }
        });
        getContentPane().add(BackToSOButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 150, 50));

        AddUserPrioTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserPrioTFActionPerformed(evt);
            }
        });
        getContentPane().add(AddUserPrioTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIs/BackgroundUsersOperations.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToSOButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToSOButtActionPerformed
        this.setVisible(false);
        OperativeSistemUI ventanaso = new OperativeSistemUI();
        ventanaso.setVisible(true);
        
    }//GEN-LAST:event_BackToSOButtActionPerformed

    private void AddUserButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserButtActionPerformed
        String nombre = AddUserNameTF.getText();
        String prioridad = getPrioridad().getText();
    }//GEN-LAST:event_AddUserButtActionPerformed

    private void AddUserPrioTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserPrioTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUserPrioTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersOperationsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUserButt;
    private javax.swing.JTextField AddUserNameTF;
    private javax.swing.JTextField AddUserPrioTF;
    private javax.swing.JButton BackToSOButt;
    private javax.swing.JLabel Lab1;
    private javax.swing.JLabel Lab2;
    private javax.swing.JButton RemoveUserButt;
    private javax.swing.JTextField RemoveUserTF;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
